using System;
using System.Collections.Generic;

namespace WebApiMafperu.Models
{
    public class Interactions
    {
    }
    public class Email
    {
        public string id { get; set; }
        public List<ParticipantEmail> participants { get; set; }
        public List<object> otherMediaUris { get; set; }
        public string selfUri { get; set; }
    }
    public class ParticipantEmail
    {
        public string id { get; set; }
        public string address { get; set; }
        public DateTime startTime { get; set; }
        public DateTime connectedTime { get; set; }
        public DateTime endTime { get; set; }
        public string purpose { get; set; }
        public string state { get; set; }
        public string direction { get; set; }
        public string disconnectType { get; set; }
        public bool held { get; set; }
        public bool wrapupRequired { get; set; }
        public AttributesEmail attributes { get; set; }
        public string provider { get; set; }
        public string peer { get; set; }
        public string subject { get; set; }
        public int messagesSent { get; set; }
        public bool autoGenerated { get; set; }
        public List<object> draftAttachments { get; set; }
        public bool spam { get; set; }
        public string messageId { get; set; }
        public string name { get; set; }
        public QueueEmail queue { get; set; }
        public ConversationRoutingData conversationRoutingData { get; set; }
        public ExternalContact externalContact { get; set; }
        public string wrapupPrompt { get; set; }
        public UserEmail user { get; set; }
        public int? wrapupTimeoutMs { get; set; }
        public int? alertingTimeoutMs { get; set; }
        public WrapupEmail wrapup { get; set; }
        public DateTime? startAcwTime { get; set; }
        public DateTime? endAcwTime { get; set; }
    }
    public class AttributesEmail
    {
    }
    public class ExternalContact
    {
        public string id { get; set; }
        public string selfUri { get; set; }
    }
    public class QueueEmail
    {
        public string id { get; set; }
        public string selfUri { get; set; }
    }
    public class ConversationRoutingData
    {
        public QueueEmail queue { get; set; }
        public int priority { get; set; }
        public List<object> skills { get; set; }
        public List<object> scoredAgents { get; set; }
    }
    public class UserEmail
    {
        public string id { get; set; }
        public string selfUri { get; set; }
    }
    public class WrapupEmail
    {
        public string code { get; set; }
        public string notes { get; set; }
        public List<object> tags { get; set; }
        public int durationSeconds { get; set; }
        public DateTime endTime { get; set; }
    }
}
public class To
{
    public string email { get; set; }
    public string name { get; set; }
}
public class From
{
    public string email { get; set; }
    public string name { get; set; }
}
public class Entity
{
    public string id { get; set; }
    public List<To> to { get; set; }
    public List<object> cc { get; set; }
    public List<object> bcc { get; set; }
    public From from { get; set; }
    public string subject { get; set; }
    public List<object> attachments { get; set; }
    public DateTime time { get; set; }
    public bool historyIncluded { get; set; }
    public string selfUri { get; set; }
}
public class MessageEmail
{
    public List<Entity> entities { get; set; }
    public int pageSize { get; set; }
    public int pageNumber { get; set; }
    public int total { get; set; }
    public string firstUri { get; set; }
    public string selfUri { get; set; }
    public string lastUri { get; set; }
    public int pageCount { get; set; }
}
public class MessageDetail
{
    public string id { get; set; }
    public List<To> to { get; set; }
    public List<object> cc { get; set; }
    public List<object> bcc { get; set; }
    public From from { get; set; }
    public string subject { get; set; }
    public List<object> attachments { get; set; }
    public string textBody { get; set; }
    public DateTime time { get; set; }
    public bool historyIncluded { get; set; }
    public string selfUri { get; set; }
}
